"""cria scout_profiles e club_profiles

Revision ID: 9f57e595dc96
Revises: ec4e15ee81af
Create Date: 2026-09-04 00:36:41.737240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f57e595dc96'
down_revision: Union[str, Sequence[str], None] = 'ec4e15ee81af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('legal_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(length=14), nullable=True),
    sa.Column('categories', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_club_profiles_cnpj'), 'club_profiles', ['cnpj'], unique=False)
    op.create_index(op.f('ix_club_profiles_state'), 'club_profiles', ['state'], unique=False)
    op.create_index('ix_club_profiles_state_city', 'club_profiles', ['state', 'city'], unique=False)
    op.create_table('scout_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credential', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_scout_profiles_organization'), 'scout_profiles', ['organization'], unique=False)
    op.create_index(op.f('ix_scout_profiles_state'), 'scout_profiles', ['state'], unique=False)
    op.create_index('ix_scout_profiles_state_city', 'scout_profiles', ['state', 'city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scout_profiles_state_city', table_name='scout_profiles')
    op.drop_index(op.f('ix_scout_profiles_state'), table_name='scout_profiles')
    op.drop_index(op.f('ix_scout_profiles_organization'), table_name='scout_profiles')
    op.drop_table('scout_profiles')
    op.drop_index('ix_club_profiles_state_city', table_name='club_profiles')
    op.drop_index(op.f('ix_club_profiles_state'), table_name='club_profiles')
    op.drop_index(op.f('ix_club_profiles_cnpj'), table_name='club_profiles')
    op.drop_table('club_profiles')
    # ### end Alembic commands ###
